//? config
@name = courses
@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@baseUrl = http://{{host}}/{{name}}
### Auth Tokens
@UserToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWY1ZmVpdmwwMDAwb2U2OXlsYnBtb3VuIiwiZW1haWwiOiJ0ZXN0LnVzZXJAZWR1LmNvbSIsImlhdCI6MTc1Njk5MTU0NywiZXhwIjoxNzU3NTk2MzQ3fQ.s7rzgTlUAK-PksoutZ0oPEnHSDJwk4lfkknaEgCgooo
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWY0cmdqYjkwMDFob2UwbzFxdTBmMGVxIiwiZW1haWwiOiJhZG1pbkBlZHUuY29tIiwiaWF0IjoxNzU2OTkxNzU3LCJleHAiOjE3NTc1OTY1NTd9.4xk5sVYfZlMMcaTLh2yGEO1LQ9F700E9R22izHJO4ew
@teacherToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWY0cmdqanMwMDFrb2UwbzB3endqMGhxIiwiZW1haWwiOiJ0ZWFjaGVyQGVkdS5jb20iLCJpYXQiOjE3NTY5OTM2NzEsImV4cCI6MTc1NzU5ODQ3MX0.itp_vU6j9lyDL5qYani3inAyYPDcTGBr9vRiY1aPkmg
@studentToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWY0cmdqcjkwMDFub2Uwb2w1YjRyM3VzIiwiZW1haWwiOiJzdHVkZW50QGVkdS5jb20iLCJpYXQiOjE3NTY5OTE4MTQsImV4cCI6MTc1NzU5NjYxNH0.1mWq49IIl4zSTig1Bwmd-S8iMjh5l4hFxUXiS0byc8c
### Ids for testing
@courseId = cmf5gh6mm0003oe69bbqa8qfx
@teacherId = cmf4rgjjs001koe0o0wzwj0hq
### Health Check
GET http://localhost:3000/health HTTP/1.1

### All courses
GET {{baseUrl}} HTTP/1.1
Authorization: Bearer {{studentToken}}

### Course by ID
GET {{baseUrl}}/{{courseId}} HTTP/1.1
Authorization: Bearer {{teacherToken}}

### Create a course
POST {{baseUrl}} HTTP/1.1
Authorization: Bearer {{teacherToken}}
content-type: application/json

{
  "name": "Programación Avanzada",
  "description": "Curso de programación avanzada con TypeScript y Node.js",
  "code": "UNASUTH001",
  "credits": 4,
  "teacherIds": ["{{teacherId}}"]
}

### Update a user
PUT {{baseUrl}}/{{courseId}} HTTP/1.1
Authorization: Bearer {{adminToken}}
content-type: application/json

{
  "name": "Programación Avanzada Actualizada",
  "credits": 5,
  "description": "Curso actualizado de programación avanzada"
}

### Delete logic a user
DELETE {{baseUrl}}/cmf5fv1di0001oe69nefl26ds HTTP/1.1
Authorization: Bearer {{adminToken}}

### Enroll a student in a course
POST {{baseUrl}}/cmf5gp1m50007oe69u0z35fsa/enroll HTTP/1.1
Authorization: Bearer {{teacherToken}}
content-Type: application/json

{
  "studentId": "cmf4rgjr9001noe0ol5b4r3us"
}

### Un enroll a student in a course
POST {{baseUrl}}/cmf5gp1m50007oe69u0z35fsa/unenroll HTTP/1.1
Authorization: Bearer {{teacherToken}}
content-Type: application/json

{
  "studentId": "cmf4rgjr9001noe0ol5b4r3us"
}