//? config
@name = grades
@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@baseUrl = http://{{host}}/{{name}}
### Auth Tokens
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWZhMnEybHowMDFxanhwaXJ4cmhqNWxrIiwiZW1haWwiOiJhZG1pbkBlZHUuY29tIiwiaWF0IjoxNzU3MjcyOTg2LCJleHAiOjE3NTc4Nzc3ODZ9.yI62q4yrP4V_6qTBsiqRUiGGw0kaLAssRqqT8sdW3Fw
@UserToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWY1ZmVpdmwwMDAwb2U2OXlsYnBtb3VuIiwiZW1haWwiOiJ0ZXN0LnVzZXJAZWR1LmNvbSIsImlhdCI6MTc1Njk5MTU0NywiZXhwIjoxNzU3NTk2MzQ3fQ.s7rzgTlUAK-PksoutZ0oPEnHSDJwk4lfkknaEgCgooo
@teacherToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWY0cmdqanMwMDFrb2UwbzB3endqMGhxIiwiZW1haWwiOiJ0ZWFjaGVyQGVkdS5jb20iLCJpYXQiOjE3NTY5OTM2NzEsImV4cCI6MTc1NzU5ODQ3MX0.itp_vU6j9lyDL5qYani3inAyYPDcTGBr9vRiY1aPkmg
@studentToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWY0cmdqcjkwMDFub2Uwb2w1YjRyM3VzIiwiZW1haWwiOiJzdHVkZW50QGVkdS5jb20iLCJpYXQiOjE3NTY5OTE4MTQsImV4cCI6MTc1NzU5NjYxNH0.1mWq49IIl4zSTig1Bwmd-S8iMjh5l4hFxUXiS0byc8c
### Ids for testing
@courseId = cmf5gh6mm0003oe69bbqa8qfx
@teacherId = cmf4rgjjs001koe0o0wzwj0hq
### Health Check
GET http://localhost:3000/health HTTP/1.1

### Calificaciones de estudiante
GET {{baseUrl}}/student?studentId=cmfa2q2zm001wjxpiv45m5ywh&semester=2024-2 HTTP/1.1
Authorization: Bearer {{adminToken}}

### Calificaciones de curso
GET {{baseUrl}}/course?courseId=cmfa2q2zw001zjxpi4gfdlqo7&semester=2024-2 HTTP/1.1
Authorization: Bearer {{adminToken}}

### transcript
GET {{baseUrl}}/transcript/cmfa2q2zm001wjxpiv45m5ywh HTTP/1.1
Authorization: Bearer {{adminToken}}

### Create qualification
POST {{baseUrl}} HTTP/1.1
Authorization: Bearer {{adminToken}}
content-type: application/json

{
  "studentId": "cmfa2q2zm001wjxpiv45m5ywh",
  "courseId": "cmfa2q2zw001zjxpi4gfdlqo7",
  "value": 85,
  "assessmentType": "exam",
  "assessmentName": "Examen 2do Parcial",
  "maxScore": 100,
  "weight": 0.3,
  "semester": "2024-2",
  "comments": "Excelente desempeño",
  "gradedDate": "2024-03-15T00:00:00.000Z"
}

### Update a qualification
PUT {{baseUrl}}/cmfa3qxeq000djxr2n62p9vqn HTTP/1.1
Authorization: Bearer {{adminToken}}
content-type: application/json

{
  "value": 90,
  "comments": "Revisión adicional, mejoró la calificación"
}

### Delete logic a user
DELETE {{baseUrl}}/grades/cmf5fv1di0001oe69nefl26ds HTTP/1.1
Authorization: Bearer {{adminToken}}
 
### static data - create qualification
 POST {{baseUrl}}/statistics HTTP/1.1
Authorization: Bearer {{adminToken}}
content-type: application/json

{
  "grades": [85, 90, 78, 92, 88, 95, 82, 79, 91, 87]
}